sudo: false
language: node_js
node_js:
  - 8
  - 10
  - node
script:
  - npm install
  - npm test
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
